'use strict';

var path = require('path');

var BUILD_DIR = path.resolve(process.cwd(), 'build');
var WikidataBuilder = require('./src/WikidataBuilder');

module.exports = function(grunt) {

	grunt.loadNpmTasks('grunt-contrib-jshint');
	grunt.loadNpmTasks('grunt-contrib-watch');

	grunt.registerTask('default', ['jshint']);

	grunt.initConfig({
		jshint: {
			options: {
				jshintrc: '.jshintrc'
			},
			projectBase: {
				src: ['*.js', '*.json']
			}
		},

		watch: {
			all: {
				files: ['**/*.js', '*.json'],
				tasks: ['default']
			},
			projectBase: {
				files: '<%= jshint.projectBase.src %>',
				tasks: ['jshint:projectBase']
			}
		}
	});

	grunt.task.registerTask(
		'build',
		'Create a new build',
		function() {
			var builder = new WikidataBuilder(
				grunt,
				this.async(),
				BUILD_DIR + '/' + Math.round((new Date()).getTime() / 1000 ).toString() + '/'
			);

			builder.build();
		}
	);

	grunt.task.registerTask(
		'clean',
		'Remove all resources generated by this app, including builds',
		function() {
			var done = this.async();
			var exec = require('child_process').exec;

			exec(
				'rm -rf ' + BUILD_DIR,
				function(error, stdout, stderr) {
					done(error===null);

					if (stdout !== '') {
						grunt.log.writeln(stdout);
					}

					if (stderr !== '') {
						grunt.log.writeln(stderr);
					}
				}
			);
		}
	);

};
