'use strict';

var path = require('path');

var WikidataBuilder = require('./src/WikidataBuilder');
var appConfig = require('./config');

module.exports = function(grunt) {

	grunt.loadNpmTasks('grunt-contrib-nodeunit');
	grunt.loadNpmTasks('grunt-contrib-jshint');
	grunt.loadNpmTasks('grunt-contrib-watch');

	grunt.registerTask('default', ['integrate']);

	grunt.initConfig({
		nodeunit: {
			quick: {
				src: ['test/quick/**/*Test.js']
			},
			slow: {
				src: ['test/slow/**/*Test.js']
			}
		},

		jshint: {
			options: {
				jshintrc: '.jshintrc'
			},
			projectBase: {
				src: ['*.js', '*.json']
			},
			all: {
				src: [
					'src/**/*.js',
					'test/**/*.js',
					'*.json'
				]
			}
		},

		watch: {
			all: {
				files: '<%= jshint.all.src %>',
				tasks: ['quick']
			},
			projectBase: {
				files: '<%= jshint.projectBase.src %>',
				tasks: ['jshint:projectBase']
			}
		}
	});

	grunt.task.registerTask(
		'integrate',
		['jshint', 'nodeunit']
	);

	grunt.task.registerTask(
		'quick',
		['jshint', 'nodeunit:quick']
	);

	grunt.task.registerTask(
		'build',
		'Create a new build',
		function(build) {
			var dirOfThisBuild = build || appConfig.DEFAULT_BUILD;

			var buildConfig = require(path.resolve(appConfig.BUILD_CONFIG_DIR, dirOfThisBuild, 'config'));
			var resourceDir = path.resolve(appConfig.BUILD_CONFIG_DIR, dirOfThisBuild, 'build_resources');

			var builder = new WikidataBuilder(
				grunt,
				{
					'buildDir': path.resolve(appConfig.BUILD_DIR, buildConfig.BUILD_DIR),
					'topLevelDir': buildConfig.NAME_OF_TOP_DIR,
					'resourceDir': resourceDir,
					'composerCommand': appConfig.COMPOSER_COMMAND
				}
			);

			var done = this.async();

			builder.once(
				'done',
				function(error) {
					done(error===null);
				}
			);

			builder.build();
		}
	);

	grunt.task.registerTask(
		'clean',
		'Remove all resources generated by this app, including builds',
		function() {
			var done = this.async();
			var exec = require('child_process').exec;

			exec(
				'rm -rf ' + appConfig.BUILD_DIR,
				function(error, stdout, stderr) {
					done(error===null);

					if (stdout !== '') {
						grunt.log.writeln(stdout);
					}

					if (stderr !== '') {
						grunt.log.writeln(stderr);
					}
				}
			);
		}
	);

};
