'use strict';

var path = require('path');

module.exports = function(grunt) {

	grunt.option('stack', true);

	grunt.loadNpmTasks('grunt-contrib-nodeunit');
	grunt.loadNpmTasks('grunt-contrib-jshint');
	grunt.loadNpmTasks('grunt-contrib-watch');

	grunt.registerTask('default', ['integrate']);

	grunt.initConfig({
		nodeunit: {
			quick: {
				src: ['test/quick/**/*Test.js']
			},
			slow: {
				src: ['test/slow/**/*Test.js']
			}
		},

		jshint: {
			options: {
				jshintrc: '.jshintrc'
			},
			projectBase: {
				src: ['*.js', '*.json']
			},
			all: {
				src: [
					'src/**/*.js',
					'test/**/*.js',
					'*.json'
				]
			}
		},

		watch: {
			all: {
				files: '<%= jshint.all.src %>',
				tasks: ['quick']
			},
			projectBase: {
				files: '<%= jshint.projectBase.src %>',
				tasks: ['jshint:projectBase']
			}
		}
	});

	grunt.task.registerTask(
		'test',
		['jshint', 'nodeunit']
	);

	grunt.task.registerTask(
		'integrate',
		['test']
	);

	grunt.task.registerTask(
		'quick',
		['jshint', 'nodeunit:quick']
	);

	grunt.task.registerTask(
		'build',
		'Create a new build',
		function(buildName, packageName, packageVersion) {
			var BuildTask = require('./src/task/BuildTask');
			var task = new BuildTask(require('./appConfig'));

			task.run(
				{
					'buildName': buildName,
					'packageName': packageName,
					'packageVersion': packageVersion
				},
				this.async()
			);
		}
	);

	grunt.task.registerTask(
		'mkconf',
		'Create default new configuration',
		function(configName) {
			if ( !configName ) {
				grunt.fail.fatal('Need to provide a config name');
			}
			var done = this.async();

			var ConfigDirCreator = require('./src/ConfigDirCreator');
			var dirCreator = new ConfigDirCreator(require('./appConfigappConfig').BUILD_CONFIG_DIR);

			dirCreator.once('done', function() {
				done();
			});

			dirCreator.create(configName);
		}
	);

	grunt.task.registerTask(
		'clean',
		'Remove all resources generated by this app, including builds',
		function() {
			var done = this.async();
			var exec = require('child_process').exec;

			exec(
				'rm -rf ' + require('./appConfig').BUILD_DIR,
				function(error, stdout, stderr) {
					done(error===null);

					if (stdout !== '') {
						grunt.log.writeln(stdout);
					}

					if (stderr !== '') {
						grunt.log.writeln(stderr);
					}
				}
			);
		}
	);

	grunt.task.registerTask(
		'rebuild',
		'Run clean followed by build with the provided arguments',
		function() {
			grunt.task.run([
				'clean',
				['build'].concat(Array.prototype.slice.call(arguments)).join(":")
			]);
		}
	);

};
